-- This file is automatically generated by @rad/sqlite-generator.
-- @generated 36da3a3c-42c7-4bb5-a74d-dc43937c0db6
-- migrate:up
CREATE TABLE "tbl" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "createdAt" TEXT NOT NULL,
  "updatedAt" TEXT NOT NULL,
  "isActive" INTEGER NOT NULL,
  "parentId" TEXT,
  "content" TEXT NOT NULL,
  "contentLength" INTEGER NOT NULL GENERATED ALWAYS AS (LENGTH(content)),
  "extra" TEXT NOT NULL,
  FOREIGN KEY ( "parentId" ) REFERENCES "tbl" ( "id" )
);

-- migrate:down
DROP TABLE "tbl";
