import * as fs from "fs";

/// If a file contains this string, it's assumed that it's safe to overwrite.
export const generatedTag = "36da3a3c-42c7-4bb5" + "-a74d-dc43937c0db6";

export const generatedBanner = (generator: string, c: string = "//") =>
  [
    c + " This file is automatically generated by " + generator + ".",
    c + " @generated " + generatedTag,
  ].join("\n");

export async function writeGeneratedFile(path: string, content: string) {
  if (content.indexOf(generatedTag) === -1) {
    throw new Error("writing generated file without generatedBanner");
  }
  await fs.promises
    .writeFile(path, content, { flag: "wx" })
    .catch(async (e) => {
      if (e.code === "EEXIST") {
        const existingContent = await fs.promises.readFile(path, "utf-8");
        if (existingContent.indexOf(generatedTag) !== -1) {
          return await fs.promises.writeFile(path, content, { flag: "w" });
        } else {
          throw new Error(
            `file ${path} already exists and is not a generated file`
          );
        }
      }
      throw e;
    });
}
